# Generated by Django 3.1.2 on 2020-10-21 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(max_length=10)),
                ('n03_002', models.CharField(max_length=20)),
                ('n03_003', models.CharField(max_length=20)),
                ('n03_004', models.CharField(max_length=20)),
                ('n03_007', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=6668)),
            ],
        ),
    ]
